// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZPA7MaF47kcX7zq5Llw5QpRtH31joubs',
    appId: '1:565812536313:web:949bd0bce33a7c94149328',
    messagingSenderId: '565812536313',
    projectId: 'prueba2-cdb2e',
    authDomain: 'prueba2-cdb2e.firebaseapp.com',
    storageBucket: 'prueba2-cdb2e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-MhlpeYW3EF6_mhRzsz6IpdmtGi8g6Y0',
    appId: '1:565812536313:android:98e834032be7588c149328',
    messagingSenderId: '565812536313',
    projectId: 'prueba2-cdb2e',
    storageBucket: 'prueba2-cdb2e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARfrL5P-1qp1bI4g1UuI3ONtPJcDDCELs',
    appId: '1:565812536313:ios:db20e1b9921f38a6149328',
    messagingSenderId: '565812536313',
    projectId: 'prueba2-cdb2e',
    storageBucket: 'prueba2-cdb2e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARfrL5P-1qp1bI4g1UuI3ONtPJcDDCELs',
    appId: '1:565812536313:ios:db20e1b9921f38a6149328',
    messagingSenderId: '565812536313',
    projectId: 'prueba2-cdb2e',
    storageBucket: 'prueba2-cdb2e.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZPA7MaF47kcX7zq5Llw5QpRtH31joubs',
    appId: '1:565812536313:web:52176a4643a555f8149328',
    messagingSenderId: '565812536313',
    projectId: 'prueba2-cdb2e',
    authDomain: 'prueba2-cdb2e.firebaseapp.com',
    storageBucket: 'prueba2-cdb2e.appspot.com',
  );
}
